# Generated by Django 5.0.2 on 2024-03-04 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PenduDjangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VotreModele',
            new_name='ModelScore',
        ),
    ]
