# Generated by Django 5.0.2 on 2024-03-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VotreModele',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('win', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5)),
            ],
        ),
    ]
